title: Tay Che Makes
description: A portfolio of completed and ongoing engineering and design projects. Includes rendered SolidWorks models of past and ongoing projects. All work (unless otherwise stated) was completed by Taylor Chevalier. Pronounced "Tay-Shay-Makes"
#url: https://tchevalier3.github.io
